apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nodename
  name: nodename
spec:
  containers:
  - image: redis
    name: nodename
    resources: {}
  nodeName: gke-k8s-hindi-day-8-pool-day8-3916688d-sz0d
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
